services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # Next.js
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
      # Shared/OnchainKit variables

      NEXT_PUBLIC_ONCHAINKIT_PROJECT_NAME: ${NEXT_PUBLIC_ONCHAINKIT_PROJECT_NAME}
      NEXT_PUBLIC_URL: ${NEXT_PUBLIC_URL}
      NEXT_PUBLIC_ICON_URL: ${NEXT_PUBLIC_ICON_URL}
      NEXT_PUBLIC_ONCHAINKIT_API_KEY: ${NEXT_PUBLIC_ONCHAINKIT_API_KEY}
      NEXT_PUBLIC_APP_ICON: ${NEXT_PUBLIC_APP_ICON}
      # Frame metadata

      FARCASTER_HEADER: ${FARCASTER_HEADER}
      FARCASTER_PAYLOAD: ${FARCASTER_PAYLOAD}
      FARCASTER_SIGNATURE: ${FARCASTER_SIGNATURE}
      # Optional Frame metadata items below
      NEXT_PUBLIC_APP_SUBTITLE: ${NEXT_PUBLIC_APP_SUBTITLE}
      NEXT_PUBLIC_APP_DESCRIPTION: ${NEXT_PUBLIC_APP_DESCRIPTION}
      NEXT_PUBLIC_APP_SPLASH_IMAGE: ${NEXT_PUBLIC_APP_SPLASH_IMAGE}
      NEXT_PUBLIC_SPLASH_BACKGROUND_COLOR: ${NEXT_PUBLIC_SPLASH_BACKGROUND_COLOR}
      NEXT_PUBLIC_APP_PRIMARY_CATEGORY: ${NEXT_PUBLIC_APP_PRIMARY_CATEGORY}
      NEXT_PUBLIC_APP_HERO_IMAGE: ${NEXT_PUBLIC_APP_HERO_IMAGE}
      NEXT_PUBLIC_APP_TAGLINE: ${NEXT_PUBLIC_APP_TAGLINE}
      NEXT_PUBLIC_APP_OG_TITLE: ${NEXT_PUBLIC_APP_OG_TITLE}
      NEXT_PUBLIC_APP_OG_DESCRIPTION: ${NEXT_PUBLIC_APP_OG_DESCRIPTION}
      NEXT_PUBLIC_APP_OG_IMAGE: ${NEXT_PUBLIC_APP_OG_IMAGE}
      PRICE_API_BASE_URL: ${PRICE_API_BASE_URL}
    ports:
      - "3006:3000"
    restart: unless-stopped